import type { Metadata } from "next";
import "./globals.css";
import dynamic from "next/dynamic";
import ClientOnly from "./ClientOnly";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "화이트터스크",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <ClientOnly>
          <Providers>
            {children}
          </Providers>
        </ClientOnly>
      </body>
    </html>
  );
}
