import type { Metadata } from "next";
import "./globals.css";
import ClientOnly from "./ClientOnly";
import Providers from "./providers";
import Header from "./header/Header";
import StoreClient from "./StoreClient";

export const metadata: Metadata = {
  title: "화이트터스크",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <ClientOnly>
          <StoreClient>
            <Providers>
              <Header/>
              {children}
            </Providers>
          </StoreClient>
        </ClientOnly>
      </body>
    </html>
  );
}
