import { useEffect, useMemo, useState } from "react";
import { addToast, Button, Card, CardBody, Input, Select, SelectItem, Switch, Textarea } from "@heroui/react";
import { LoadingComponent } from "../../UtilsCompnents";
import type { DiscordGuildResources, DiscordVoiceButtonConfig, DiscordVoiceConfig } from "../model/discordGuildTypes";

type Props = { selectedGuildId: string, botInstalled: boolean };
type Resources = DiscordGuildResources & { voiceConfig: DiscordVoiceConfig | null };
type Form = { channelId: string, embedTitle: string, embedDescription: string, autoMove: boolean, buttons: DiscordVoiceButtonConfig[] };
const makeButton = (index: number): DiscordVoiceButtonConfig => ({ id: `button-${index + 1}`, label: `음성 채널 ${index + 1}`, channelName: `레이드 파티 ${index + 1}`, categoryId: "", userLimit: null, maxChannels: 1 });
const defaultForm: Form = { channelId: "", embedTitle: "레이드 음성 채널 생성", embedDescription: "아래 버튼을 눌러 레이드 음성 채널을 생성하세요.", autoMove: false, buttons: [makeButton(0)] };
function toForm(config: DiscordVoiceConfig | null): Form { return config ? { channelId: config.channelId, embedTitle: config.embedTitle, embedDescription: config.embedDescription, autoMove: config.autoMove, buttons: config.buttons } : { ...defaultForm, buttons: [makeButton(0)] }; }
async function responseError(response: Response, fallback: string): Promise<Error> { const data = await response.json().catch(() => null) as { error?: unknown } | null; return new Error(typeof data?.error === "string" ? data.error : fallback); }

export default function DiscordVoiceForm({ selectedGuildId, botInstalled }: Props) {
    const [resources, setResources] = useState<Resources | null>(null); const [saved, setSaved] = useState<DiscordVoiceConfig | null>(null); const [form, setForm] = useState<Form>({ ...defaultForm, buttons: [makeButton(0)] }); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [publishing, setPublishing] = useState(false);
    const dirty = useMemo(() => JSON.stringify(form) !== JSON.stringify(toForm(saved)), [form, saved]);
    useEffect(() => { if (!selectedGuildId || !botInstalled) { setResources(null); return; } setLoading(true); fetch(`/api/integrations/discord/guilds/${selectedGuildId}/voice`).then(async response => { if (!response.ok) throw await responseError(response, "음성 채널 설정을 불러오지 못했습니다."); return response.json() as Promise<Resources>; }).then(data => { setResources(data); setSaved(data.voiceConfig); setForm(toForm(data.voiceConfig)); }).catch(error => addToast({ title: "불러오기 실패", description: error instanceof Error ? error.message : "음성 채널 설정을 불러오지 못했습니다.", color: "danger" })).finally(() => setLoading(false)); }, [selectedGuildId, botInstalled]);
    const update = <K extends keyof Form>(key: K, value: Form[K]) => setForm(current => ({ ...current, [key]: value }));
    const updateButton = (index: number, key: keyof DiscordVoiceButtonConfig, value: string | number | null) => setForm(current => ({ ...current, buttons: current.buttons.map((button, buttonIndex) => buttonIndex === index ? { ...button, [key]: value } : button) }));
    async function save(publish: boolean) { setSaving(!publish); setPublishing(publish); try { const put = await fetch(`/api/integrations/discord/guilds/${selectedGuildId}/voice`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); if (!put.ok) throw await responseError(put, "음성 채널 설정을 저장하지 못했습니다."); let config = (await put.json() as { config: DiscordVoiceConfig }).config; if (publish) { const post = await fetch(`/api/integrations/discord/guilds/${selectedGuildId}/voice`, { method: "POST" }); if (!post.ok) throw await responseError(post, "음성 채널 메시지를 전송하지 못했습니다."); config = (await post.json() as { config: DiscordVoiceConfig }).config; } setSaved(config); setForm(toForm(config)); addToast({ title: publish ? "메시지 반영 완료" : "저장 완료", description: publish ? "Discord에 음성 채널 생성 메시지를 반영했습니다.": "설정을 저장했습니다.", color: "success" }); } catch (error) { addToast({ title: "처리 실패", description: error instanceof Error ? error.message : "요청을 처리하지 못했습니다.", color: "danger" }); } finally { setSaving(false); setPublishing(false); } }
    if (loading) return <LoadingComponent heightStyle="min-h-[360px]" message="음성 채널 설정을 불러오고 있어요"/>;
    if (!resources) return <Card><CardBody>Discord 서버와 봇 설치 상태를 확인해 주세요.</CardBody></Card>;
    return <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_280px]">
        <div className="space-y-5">
            <Card><CardBody className="gap-4"><div><p className="font-bold">음성 채널 생성 메시지</p><p className="text-sm text-default-500">버튼을 누르면 설정한 카테고리에 임시 음성 채널을 생성합니다.</p></div>
                <Select label="메시지 전송 채널" selectedKeys={form.channelId ? [form.channelId] : []} onSelectionChange={keys => update("channelId", String(Array.from(keys)[0] ?? ""))}>{resources.channels.map(channel => <SelectItem key={channel.id}>{channel.name}</SelectItem>)}</Select>
                <Input label="임베드 제목" value={form.embedTitle} onValueChange={value => update("embedTitle", value)} maxLength={256}/><Textarea label="임베드 본문" value={form.embedDescription} onValueChange={value => update("embedDescription", value)} maxLength={4096}/>
                <div className="flex items-center justify-between rounded-lg bg-default-50 p-3"><div><p className="font-semibold">생성 후 자동 이동</p><p className="text-xs text-default-500">사용자가 음성 채널에 접속 중일 때만 이동합니다.</p></div><Switch isSelected={form.autoMove} onValueChange={value => update("autoMove", value)} color="success"/></div>
             </CardBody></Card>
            <Card><CardBody className="gap-4"><div className="flex items-center justify-between"><div><p className="font-bold">음성 채널 버튼</p><p className="text-sm text-default-500">1~5개까지 설정할 수 있습니다.</p></div><Button size="sm" variant="flat" isDisabled={form.buttons.length >= 5} onPress={() => update("buttons", [...form.buttons, makeButton(form.buttons.length)])}>버튼 추가</Button></div>
                {form.buttons.map((button, index) => <div key={button.id} className="space-y-3 rounded-xl border border-default-200 p-4"><div className="flex items-center justify-between"><p className="font-semibold">버튼 {index + 1}</p><Button size="sm" color="danger" variant="light" isDisabled={form.buttons.length <= 1} onPress={() => update("buttons", form.buttons.filter((_, buttonIndex) => buttonIndex !== index))}>삭제</Button></div><Input label="버튼 문구" value={button.label} onValueChange={value => updateButton(index, "label", value)} maxLength={80}/><Input label="생성할 음성 채널명" value={button.channelName} onValueChange={value => updateButton(index, "channelName", value)} maxLength={100}/><Select label="생성 카테고리" selectedKeys={button.categoryId ? [button.categoryId] : []} onSelectionChange={keys => updateButton(index, "categoryId", String(Array.from(keys)[0] ?? ""))}>{resources.categories.map(category => <SelectItem key={category.id}>{category.name}</SelectItem>)}</Select><div className="grid gap-3 sm:grid-cols-2"><Input type="number" label="최대 인원 (빈 값: 무제한)" min={1} max={99} value={button.userLimit ? String(button.userLimit) : ""} onValueChange={value => updateButton(index, "userLimit", value ? Number(value) : null)}/><Input type="number" label="동시 생성 최대 수" min={1} max={25} value={String(button.maxChannels)} onValueChange={value => updateButton(index, "maxChannels", Number(value) || 1)}/></div></div>)}
             </CardBody></Card>
            <div className="flex flex-wrap justify-end gap-2"><Button color="primary" isDisabled={!dirty || !resources.botCanManageChannels} isLoading={saving} onPress={() => save(false)}>설정 저장</Button><Button color="success" isDisabled={!resources.botCanManageChannels} isLoading={publishing} onPress={() => save(true)}>Discord에 메시지 반영</Button></div>
        </div>
        <Card><CardBody><p className="font-bold">Discord 미리보기</p><div className="mt-3 rounded-xl bg-[#313338] p-4 text-white"><p className="font-bold">{form.embedTitle || "임베드 제목"}</p><p className="mt-2 whitespace-pre-wrap text-sm text-gray-300">{form.embedDescription || "임베드 본문"}</p><div className="mt-4 flex flex-wrap gap-2">{form.buttons.map(button => <span key={button.id} className="rounded bg-[#5865f2] px-3 py-2 text-xs font-semibold">{button.label || "버튼"}</span>)}</div></div>{!resources.botCanManageChannels ? <p className="mt-3 text-sm text-danger">봇에 채널 관리 권한이 필요합니다.</p> : null}</CardBody></Card>
    </div>;
}
