'use client';

import { Button, Checkbox, Progress, Select, SelectItem, Tab, Tabs } from '@heroui/react';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { actionFromAttempt, breathRequirements, calculateHoning, getHoningAttempt, stoneRequirements } from '../lib/honingCalculator';
import { findHoningRate, getHoningLevels, type HoningPart, type HoningTier } from '../data/honingRates';
import type { HoningAttempt, HoningBreathAmounts, HoningCalculationInput, HoningMode, OwnedMaterialKey, OwnedMaterials } from '../model/calculatorTypes';
import type { HoningMaterialPriceData } from '../model/types';

type SimulationMode = 'optimal' | 'custom';
type SimulationSpeed = 'fast' | 'normal' | 'slow';
type SimulationRow = HoningAttempt & { success: boolean };
type SimulationRecord = { id: string; createdAt: number; tier: HoningTier; part: HoningPart; level: number; mode: SimulationMode; attempts: number; artisan: number; cost: number };
type Runtime = { failures: number; artisan: number; attempts: SimulationRow[]; cost: number; baseGold: number; materials: Record<string, { amount: number; name: string; icon: string | null }> };
type Props = { priceData: HoningMaterialPriceData; embedded?: boolean; tier: HoningTier; part: HoningPart; level: string; setTier: (value: HoningTier) => void; setPart: (value: HoningPart) => void; setLevel: (value: string) => void; owned: OwnedMaterials; ownedGold: number; onOwnedChange: React.Dispatch<React.SetStateAction<OwnedMaterials>>; onGoldChange: React.Dispatch<React.SetStateAction<number>> };

const STORAGE_KEY = 'lotsgo:honing-simulation-records';
const SPEED_INTERVALS: Record<SimulationSpeed, number> = { fast: 100, normal: 400, slow: 800 };
const emptyOwned = {} as OwnedMaterials;
function Gold({ value }: { value: number }) { return <span className="inline-flex items-center gap-1 font-bold tabular-nums"><img src="/icons/gold.png" alt="골드" className="h-4 w-4"/>{Math.ceil(value).toLocaleString('ko-KR')}</span>; }
function MaterialIcon({ icon }: { icon: string | null }) { return icon ? <img src={icon} alt="" className="h-6 w-6 rounded object-cover"/> : <span className="h-6 w-6 rounded bg-default-100 dark:bg-white/10"/>; }
function getBookKey(tier: HoningTier, part: HoningPart, level: number): OwnedMaterialKey | null { if (part === '완갑') return null; const ranges = tier === '4티어' ? [[11, 14], [15, 18], [19, 20]] : [[12, 15], [16, 19]]; const range = ranges.find(([from, to]) => level >= from && level <= to); return range ? `${part === '무기' ? 'metallurgy' : 'tailoring'}-${tier === '4티어' ? 'upheaval' : 'thrill'}-${range[0]}-${range[1]}` as OwnedMaterialKey : null; }
function modeLabel(mode: SimulationMode) { return mode === 'optimal' ? '최적 재련' : '직접 설정'; }
function SimulationExtras({ row }: { row: SimulationRow }) { const extras = row.materials.filter((item) => item.key.includes('breath') || item.key.includes('metallurgy') || item.key.includes('tailoring')); if (!extras.length) return <span className="text-default-400">없음</span>; return <span className="flex items-center gap-2 whitespace-nowrap">{extras.map((item) => <span key={item.key} className="inline-flex items-center gap-1"><MaterialIcon icon={item.icon}/>× {item.amount.toLocaleString('ko-KR')}</span>)}</span>; }

function SimulationRequiredMaterials({ rate, priceData }: { rate: ReturnType<typeof findHoningRate>; priceData: HoningMaterialPriceData }) {
    if (!rate) return null;
    const names: Record<string, string> = { 'destiny-destruction-stone': '운명의 파괴석', 'destiny-destruction-crystal': '운명의 파괴석 결정', 'destiny-guardian-stone': '운명의 수호석', 'destiny-guardian-crystal': '운명의 수호석 결정', 'destiny-leapstone': '운명의 돌파석', 'great-destiny-leapstone': '위대한 운명의 돌파석', 'abidos-fusion-material': '아비도스 융화 재료', 'superior-abidos-fusion-material': '상급 아비도스 융화 재료', 'destiny-shard': '운명의 파편' };
    const required = [...stoneRequirements(rate), [rate.tier === '세르카' ? 'great-destiny-leapstone' : 'destiny-leapstone', rate.leapstone], [rate.tier === '세르카' ? 'superior-abidos-fusion-material' : 'abidos-fusion-material', rate.fusion], ['destiny-shard', rate.shard] as [OwnedMaterialKey, number]];
    return <div className="mt-3 rounded-xl bg-default-50 p-2.5 dark:bg-white/[0.04]"><div className="mb-1.5 flex items-center justify-between"><span className="text-xs font-bold text-default-500">1회 재련 필요 재료</span><span className="text-xs text-default-500">기본 확률 {rate.successRate}%</span></div><div className="flex flex-wrap gap-2">{required.map(([key, amount]) => { const item = priceData.items[key === 'destiny-shard' ? 'destiny-shard-pouch-large' : key as keyof typeof priceData.items]; return <div key={key} className="flex items-center gap-1.5 rounded-lg bg-default-100/80 px-2 py-1.5 text-xs dark:bg-white/[0.06]"><MaterialIcon icon={item?.icon ?? null}/><span className="whitespace-nowrap">{names[key]} × {amount.toLocaleString('ko-KR')}</span></div>; })}<div className="flex items-center gap-1.5 rounded-lg bg-default-100/80 px-2 py-1.5 text-xs dark:bg-white/[0.06]"><img src="/icons/gold.png" alt="골드" className="h-5 w-5 rounded-md object-cover"/><span className="whitespace-nowrap">기본 재련 골드 × {rate.gold.toLocaleString('ko-KR')}</span></div></div></div>;
}

export default function HoningSimulationCard({ priceData, embedded = false, tier, part, level, setTier, setPart, setLevel, owned, ownedGold, onOwnedChange, onGoldChange }: Props) {
    const [mode, setMode] = useState<SimulationMode>('optimal'); const [useLava, setUseLava] = useState(false); const [useGlacier, setUseGlacier] = useState(false); const [speed, setSpeed] = useState<SimulationSpeed>('normal'); const [running, setRunning] = useState(false); const [completed, setCompleted] = useState(false); const [rows, setRows] = useState<SimulationRow[]>([]); const [artisan, setArtisan] = useState(0); const [spentGold, setSpentGold] = useState(0); const [baseGold, setBaseGold] = useState(0); const [records, setRecords] = useState<SimulationRecord[]>([]); const [boundOnly, setBoundOnly] = useState(false); const [shortage, setShortage] = useState<string[]>([]); const runtime = useRef<Runtime>({ failures: 0, artisan: 0, attempts: [], cost: 0, baseGold: 0, materials: {} }); const executeAttemptRef = useRef<() => boolean>(() => false);
    const rate = findHoningRate(tier, part, Number(level)); const bookKey = getBookKey(tier, part, Number(level)); const breathItems = rate ? breathRequirements(rate) : []; const levelsForSelection = getHoningLevels(tier, part);
    useEffect(() => { try { const stored = localStorage.getItem(STORAGE_KEY); if (stored) setRecords(JSON.parse(stored) as SimulationRecord[]); } catch { /* 이전 기록이 손상된 경우 새 기록으로 시작합니다. */ } }, []);
    const input = useMemo<HoningCalculationInput>(() => ({ tier, part, level: Number(level), mode: 'optimal', owned: boundOnly ? owned : emptyOwned, prices: priceData, onlyOwned: boundOnly, initialFailures: runtime.current.failures, initialArtisan: runtime.current.artisan }), [tier, part, level, owned, priceData, boundOnly, rows.length, artisan]);
    const optimalCalculation = useMemo(() => rate ? calculateHoning(input) : null, [input, rate]);
    const optionsFromAttempt = (attempt: HoningAttempt) => { const options = actionFromAttempt(attempt, rate!); return { ...options, attempt: rows.length + 1, failures: runtime.current.failures, artisan: runtime.current.artisan }; };
    const fallbackAttempt = (custom: boolean) => { if (!rate) return null; const breaths: HoningBreathAmounts = {}; for (const item of breathItems) { const enabled = item.key === 'lava-breath' ? useLava : useGlacier; breaths[item.key] = enabled ? boundOnly ? Math.min(item.max, Math.floor(owned[item.key] ?? 0)) : item.max : 0; } return getHoningAttempt({ ...input, owned: emptyOwned, onlyOwned: false }, { attempt: rows.length + 1, failures: runtime.current.failures, artisan: runtime.current.artisan, useBook: custom && Boolean(bookKey && (!boundOnly || (owned[bookKey] ?? 0) >= 1)), breathAmounts: breaths }); };
    const previewAttempt = useMemo(() => { if (!rate) return null; if (mode === 'optimal' && optimalCalculation?.attempts[0]) return optionsFromAttempt(optimalCalculation.attempts[0]) && getHoningAttempt({ ...input, owned: emptyOwned, onlyOwned: false }, optionsFromAttempt(optimalCalculation.attempts[0])); return fallbackAttempt(mode === 'custom'); }, [rate, mode, optimalCalculation, input, rows.length, artisan, owned, boundOnly, useLava, useGlacier, bookKey]);
    const resetProgress = useCallback((restoreInventory = false) => { runtime.current = { failures: 0, artisan: 0, attempts: [], cost: 0, baseGold: 0, materials: {} }; setRows([]); setArtisan(0); setSpentGold(0); setBaseGold(0); setShortage([]); setCompleted(false); setRunning(false); if (restoreInventory) { /* 보유 재료는 사용자가 입력한 값을 유지합니다. */ } }, []);
    useEffect(() => { resetProgress(); }, [tier, part, level, resetProgress]);
    const missingFor = (attempt: HoningAttempt | null) => { if (!boundOnly || !attempt || !rate) return []; const missing: string[] = []; const required = new Map<string, number>(); for (const material of attempt.materials) required.set(material.key, (required.get(material.key) ?? 0) + material.amount); for (const [key, amount] of required) { const available = owned[key as OwnedMaterialKey] ?? 0; if (available < amount) missing.push(`${attempt.materials.find((item) => item.key === key)?.name ?? key} ${Math.ceil(amount - available).toLocaleString('ko-KR')}개 부족`); } if (ownedGold < rate.gold) missing.push(`기본 재련 골드 ${Math.ceil(rate.gold - ownedGold).toLocaleString('ko-KR')} 부족`); return missing; };
    const currentShortage = missingFor(previewAttempt);
    const executeAttempt = useCallback(() => { const state = runtime.current; let attempt: HoningAttempt | null = null; if (mode === 'optimal') attempt = previewAttempt; else attempt = fallbackAttempt(true); if (!attempt) return false; const missing = missingFor(attempt); if (missing.length) { setShortage(missing); setRunning(false); return false; } const success = attempt.finalChance >= 100 || Math.random() * 100 < attempt.finalChance; const row = { ...attempt, attempt: state.attempts.length + 1, success }; state.attempts = [...state.attempts, row]; state.cost += attempt.cost; state.baseGold += rate?.gold ?? 0; state.artisan = success ? attempt.artisanBefore : attempt.artisanAfter; for (const material of attempt.materials) { const current = state.materials[material.key] ?? { amount: 0, name: material.name, icon: material.icon }; state.materials[material.key] = { ...current, amount: current.amount + material.amount }; } setRows([...state.attempts]); setSpentGold(state.cost); setBaseGold(state.baseGold); setArtisan(state.artisan); setShortage([]); if (boundOnly) { const consumed = new Map<string, number>(); for (const material of attempt.materials) consumed.set(material.key, (consumed.get(material.key) ?? 0) + material.amount); onOwnedChange((current) => { const next = { ...current }; for (const [key, amount] of consumed) next[key as OwnedMaterialKey] = Math.max(0, (next[key as OwnedMaterialKey] ?? 0) - amount); return next; }); onGoldChange((current) => Math.max(0, current - (rate?.gold ?? 0))); } if (success) { setCompleted(true); setRunning(false); } else state.failures += 1; return success; }, [mode, input, rate, boundOnly, owned, ownedGold, bookKey, useLava, useGlacier, previewAttempt, onOwnedChange, onGoldChange]);
    executeAttemptRef.current = executeAttempt; useEffect(() => { if (!running) return undefined; const timer = window.setInterval(() => executeAttemptRef.current(), SPEED_INTERVALS[speed]); return () => window.clearInterval(timer); }, [running, speed]);
    const handleTierChange = (keys: Iterable<unknown>) => { const value = String(Array.from(keys)[0]) as HoningTier; setTier(value); if (value === '4티어' && part === '완갑') { setPart('무기'); setLevel('11'); } }; const handlePartChange = (keys: Iterable<unknown>) => { const value = String(Array.from(keys)[0]) as HoningPart; setPart(value); const levels = getHoningLevels(tier, value); if (!levels.includes(Number(level))) setLevel(String(levels[0])); }; const handleLevelChange = (keys: Iterable<unknown>) => setLevel(String(Array.from(keys)[0])); const toggleBoundOnly = (value: boolean) => { setBoundOnly(value); resetProgress(); }; const start = () => { if (completed) resetProgress(); setRunning(true); }; const saveRecord = () => { if (!completed || !rows.length) return; const record: SimulationRecord = { id: `${Date.now()}`, createdAt: Date.now(), tier, part, level: Number(level), mode, attempts: rows.length, artisan: rows[rows.length - 1].artisanBefore, cost: spentGold }; const next = [record, ...records]; setRecords(next); localStorage.setItem(STORAGE_KEY, JSON.stringify(next)); }; const resetRecords = () => { setRecords([]); localStorage.removeItem(STORAGE_KEY); }; const materialRows = Object.values(runtime.current.materials); const totalRecordedCost = records.reduce((sum, item) => sum + item.cost, 0); const average = records.length ? { attempts: records.reduce((sum, item) => sum + item.attempts, 0) / records.length, artisan: records.reduce((sum, item) => sum + item.artisan, 0) / records.length, cost: totalRecordedCost / records.length } : null; const canAttempt = !!previewAttempt && !completed && (!boundOnly || currentShortage.length === 0);
    return <div className={embedded ? 'flex min-h-0 flex-1 flex-col overflow-visible' : 'mt-4 rounded-2xl border border-default-200/80 bg-content1 p-4 shadow-sm dark:border-white/10 dark:bg-[#18181b] sm:p-5'}>
        <div className="mb-3"><h2 className="text-lg font-bold">재련 시뮬레이션</h2><p className="mt-1 text-xs text-default-500">거래소 시세 또는 보유 재료를 기준으로 재련을 시뮬레이션합니다.</p></div>
        <div className="grid grid-cols-1 gap-2 sm:grid-cols-3"><Select size="sm" label="장비 등급" selectedKeys={new Set([tier])} onSelectionChange={handleTierChange}><SelectItem key="4티어">4티어</SelectItem><SelectItem key="세르카">세르카</SelectItem></Select><Select size="sm" label="장비 종류" selectedKeys={new Set([part])} onSelectionChange={handlePartChange}><SelectItem key="무기">무기</SelectItem><SelectItem key="방어구">방어구</SelectItem>{tier === '세르카' ? <SelectItem key="완갑">완갑</SelectItem> : null}</Select><Select size="sm" label="강화 단계" selectedKeys={new Set([level])} renderValue={() => `${level}강`} onSelectionChange={handleLevelChange}>{levelsForSelection.map((item) => <SelectItem key={String(item)}>{item}강</SelectItem>)}</Select></div>
        <SimulationRequiredMaterials rate={rate} priceData={priceData}/>
        <Tabs className="mt-3" fullWidth selectedKey={mode} onSelectionChange={(key) => setMode(String(key) as SimulationMode)}><Tab key="optimal" title="최적 재련"/><Tab key="custom" title="직접 설정"/></Tabs>
        <div className="mt-2 grid grid-cols-1 gap-2 rounded-xl border border-default-200/80 p-2.5 dark:border-white/10 sm:grid-cols-2"><Checkbox isSelected={boundOnly} onValueChange={toggleBoundOnly}><span className="font-medium">보유 재료로만 재련</span></Checkbox>{breathItems.map((item) => <Checkbox key={item.key} isSelected={item.key === 'lava-breath' ? mode === 'optimal' || useLava : mode === 'optimal' || useGlacier} isDisabled={mode === 'optimal'} onValueChange={item.key === 'lava-breath' ? setUseLava : setUseGlacier}><span className="inline-flex items-center gap-2"><MaterialIcon icon={priceData.items[item.key]?.icon ?? null}/>{item.key === 'lava-breath' ? '용암의 숨결' : '빙하의 숨결'}</span></Checkbox>)}<p className="text-[11px] text-default-500 sm:col-span-2">최적 재련은 현재 남은 숨결 수량을 기준으로 트라이별 투입 전략을 다시 계산합니다.</p></div>
        <div className="mt-2 grid grid-cols-1 gap-1.5 rounded-xl bg-default-50 p-1.5 dark:bg-white/[0.04] sm:grid-cols-4"><Select size="sm" aria-label="재련 속도" classNames={{ trigger: 'h-9 min-h-9 bg-content1 dark:bg-white/[0.06]' }} selectedKeys={new Set([speed])} isDisabled={running} onSelectionChange={(keys) => setSpeed(String(Array.from(keys)[0]) as SimulationSpeed)}><SelectItem key="fast">빠르게</SelectItem><SelectItem key="normal">보통</SelectItem><SelectItem key="slow">느리게</SelectItem></Select><Button size="sm" color={completed ? 'success' : 'secondary'} radius="lg" className="h-9 w-full font-semibold" isDisabled={running || completed || !canAttempt} onPress={executeAttempt}>{completed ? '재련 성공' : '1회 재련'}</Button><Button size="sm" color={running ? 'danger' : 'primary'} radius="lg" className="h-9 w-full font-semibold" isDisabled={!running && !canAttempt && !completed} onPress={running ? () => setRunning(false) : start}>{running ? '자동 재련 중단' : '자동 재련'}</Button><Button size="sm" color="danger" variant="solid" radius="lg" className="h-9 w-full font-semibold" onPress={() => resetProgress()}>초기화</Button></div>
        {boundOnly && currentShortage.length ? <div className="mt-3 rounded-xl border border-danger-200 bg-danger-50 p-3 text-xs text-danger-700 dark:border-danger-500/30 dark:bg-danger-500/10 dark:text-danger-300"><p className="font-semibold">재료 부족</p><p className="mt-1">{currentShortage.join(', ')}</p></div> : null}
        <div className="mt-2 rounded-xl bg-default-50 p-2.5 dark:bg-white/[0.04]"><div className="mb-1 flex items-center justify-between text-xs"><span>장인의 기운</span><span className="font-semibold tabular-nums">{artisan.toFixed(2)}%</span></div><Progress aria-label="장인의 기운" value={artisan} color={completed ? 'success' : 'primary'}/><div className="mt-3 flex items-center justify-between text-xs"><span>누적 골드</span><Gold value={spentGold}/></div></div>
        <div className="mt-3"><h3 className="mb-1.5 text-xs font-bold text-default-500">사용 재료</h3><div className="flex flex-wrap gap-2">{materialRows.map((item) => <div key={item.name} className="flex items-center gap-1.5 rounded-lg bg-default-100/80 px-2 py-1.5 text-xs dark:bg-white/[0.06]"><MaterialIcon icon={item.icon}/><span>{item.name} × {item.amount.toLocaleString('ko-KR')}</span></div>)}<div className="flex items-center gap-1.5 rounded-lg bg-default-100/80 px-2 py-1.5 text-xs dark:bg-white/[0.06]"><img src="/icons/gold.png" alt="골드" className="h-6 w-6 rounded-md object-cover"/><span>기본 재련 골드 × {baseGold.toLocaleString('ko-KR')}</span></div></div></div>
        <div className="mt-3 grid grid-cols-1 gap-2 sm:grid-cols-2"><Button className="w-full" variant="flat" isDisabled={!completed} onPress={saveRecord}>기록하기</Button><Button className="w-full" variant="flat" color="danger" onPress={resetRecords}>기록 초기화</Button></div>
        {average ? <div className="mt-2 grid grid-cols-2 gap-2 rounded-xl bg-default-50 p-2.5 text-center text-xs dark:bg-white/[0.04] sm:grid-cols-4"><div><p className="text-default-500">평균 트라이</p><p className="mt-1 font-bold">{average.attempts.toFixed(2)}</p></div><div><p className="text-default-500">평균 장인 기운</p><p className="mt-1 font-bold">{average.artisan.toFixed(2)}%</p></div><div><p className="text-default-500">평균 비용</p><p className="mt-1"><Gold value={average.cost}/></p></div><div><p className="text-default-500">누적 골드</p><p className="mt-1"><Gold value={totalRecordedCost}/></p></div></div> : null}
        {records.length ? <><div className="mt-2 max-h-[180px] overflow-y-auto rounded-xl border border-default-200/80 dark:border-white/10"><table className="w-full min-w-[520px] text-left text-xs"><thead className="sticky top-0 bg-default-100 dark:bg-[#27272a]"><tr><th className="px-2 py-2">조건</th><th className="px-2 py-2">트라이</th><th className="px-2 py-2">장인 기운</th><th className="px-2 py-2">비용</th></tr></thead><tbody>{records.map((item) => <tr key={item.id} className="border-t border-default-100 dark:border-white/[0.06]"><td className="px-2 py-2">{item.tier} {item.part} {item.level}강<br/>{modeLabel(item.mode)}</td><td className="px-2 py-2">{item.attempts}회</td><td className="px-2 py-2">{item.artisan.toFixed(2)}%</td><td className="px-2 py-2"><Gold value={item.cost}/></td></tr>)}</tbody></table></div><p className="mt-1 text-right text-xs text-default-500">총 {records.length}개 기록</p></> : null}
        <div className="mt-4 flex min-h-0 flex-1 flex-col overflow-visible rounded-xl border border-default-200/80 dark:border-white/10"><div className="flex items-center justify-between border-b border-default-100 px-3 py-3 dark:border-white/[0.06]"><h3 className="text-sm font-bold">재련 진행 결과</h3><span className="text-xs text-default-500">{running ? `${SPEED_INTERVALS[speed] / 1000}초마다 진행 중` : completed ? '재련 성공' : rows.length ? '재련 중단' : '대기 중'}</span></div><div className="min-h-0 max-h-[500px] flex-1 overflow-auto"><table className="w-full min-w-[700px] text-left text-xs"><thead className="sticky top-0 z-10 bg-default-100 dark:bg-[#27272a]"><tr><th className="px-3 py-2">트라이</th><th className="px-3 py-2">강화 확률</th><th className="px-3 py-2">장인의 기운</th><th className="px-3 py-2">추가 재료</th><th className="px-3 py-2">트라이 비용</th><th className="px-3 py-2">결과</th></tr></thead><tbody>{[...rows].reverse().map((row) => <tr key={row.attempt} className={`border-t border-default-100 dark:border-white/[0.06] ${row.success ? 'bg-success-50/70 dark:bg-success-500/10' : ''}`}><td className="px-3 py-2">{row.attempt}트</td><td className="px-3 py-2">{row.finalChance.toFixed(2)}%</td><td className="px-3 py-2">{row.artisanBefore.toFixed(2)}% → {row.artisanAfter.toFixed(2)}%</td><td className="px-3 py-2"><SimulationExtras row={row}/></td><td className="px-3 py-2"><Gold value={row.cost}/></td><td className={`px-3 py-2 font-semibold ${row.success ? 'text-success-600 dark:text-success-400' : 'text-default-500'}`}>{row.success ? '성공' : '실패'}</td></tr>)}</tbody></table>{!rows.length ? <div className="p-10 text-center text-sm text-default-400">재련을 시작하면 진행 결과가 표시됩니다.</div> : null}</div></div>
    </div>;
}
